/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Controller;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Cylinder;
import model.SimpleCalculation;

/**
 *
 * @author pablo
 */
public class ScubaDivingView extends javax.swing.JFrame {

    Controller controller;

    /**
     * Creates new form ScubaDivingView
     * 
     * @param controller controller of the program
     */
    public ScubaDivingView(Controller controller) {
        initComponents();
        tableComplexCalculations.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Depth\\Oxygen"
                }
        ));
        cylinderPanel1.setCylinder(new Cylinder(SimpleCalculation.MIN_OXYGEN_VALUE));
        setResizable(false);
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bestMixButton = new javax.swing.JButton();
        eadButton = new javax.swing.JButton();
        smodButton = new javax.swing.JButton();
        ppo2Button = new javax.swing.JButton();
        modButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        ppo2 = new javax.swing.JComboBox();
        label1 = new java.awt.Label();
        sliderOxygen = new javax.swing.JSlider();
        Oxygen = new java.awt.TextField();
        label2 = new java.awt.Label();
        sliderDepth = new javax.swing.JSlider();
        depth = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        simpleResult = new javax.swing.JLabel();
        cylinderPanel1 = new view.CylinderPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        resultComplexCalculation = new javax.swing.JScrollPane();
        tableComplexCalculations = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        inputsComplexCalculations = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        sliderOxygenStart = new javax.swing.JSlider();
        OxygenStart = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        label9 = new java.awt.Label();
        sliderOxygenEnd = new javax.swing.JSlider();
        OxygenEnd = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        inputsComplexCalculations1 = new javax.swing.JPanel();
        label8 = new java.awt.Label();
        sliderDepthEnd = new javax.swing.JSlider();
        depthEnd = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        label10 = new java.awt.Label();
        sliderDepthStart = new javax.swing.JSlider();
        depthStart = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculations"));

        bestMixButton.setText("Best Mix");
        bestMixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestMixButtonActionPerformed(evt);
            }
        });

        eadButton.setText("EAD");
        eadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eadButtonActionPerformed(evt);
            }
        });

        smodButton.setText("SMOD");
        smodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smodButtonActionPerformed(evt);
            }
        });

        ppo2Button.setText("PPO2");
        ppo2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppo2ButtonActionPerformed(evt);
            }
        });

        modButton.setText("MOD");
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(eadButton)
                .addGap(18, 18, 18)
                .addComponent(modButton)
                .addGap(18, 18, 18)
                .addComponent(bestMixButton)
                .addGap(18, 18, 18)
                .addComponent(ppo2Button)
                .addGap(18, 18, 18)
                .addComponent(smodButton)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestMixButton)
                    .addComponent(smodButton)
                    .addComponent(ppo2Button)
                    .addComponent(modButton)
                    .addComponent(eadButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Inputs"));

        label3.setText("PPO2");

        ppo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.1", "1.2", "1.3", "1.4", "1.5", "1.6" }));
        ppo2.setToolTipText("");
        ppo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppo2ActionPerformed(evt);
            }
        });

        label1.setText("Oxygen:");

        sliderOxygen.setMajorTickSpacing(7);
        sliderOxygen.setMaximum(50);
        sliderOxygen.setMinimum(22);
        sliderOxygen.setMinorTickSpacing(1);
        sliderOxygen.setPaintLabels(true);
        sliderOxygen.setPaintTicks(true);
        sliderOxygen.setSnapToTicks(true);
        sliderOxygen.setToolTipText("");
        sliderOxygen.setValue(22);
        sliderOxygen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderOxygenStateChanged(evt);
            }
        });

        Oxygen.setEditable(false);
        Oxygen.setText("22");

        label2.setText("Depth:");

        sliderDepth.setMajorTickSpacing(10);
        sliderDepth.setMinorTickSpacing(1);
        sliderDepth.setPaintLabels(true);
        sliderDepth.setPaintTicks(true);
        sliderDepth.setSnapToTicks(true);
        sliderDepth.setToolTipText("");
        sliderDepth.setValue(0);
        sliderDepth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDepthStateChanged(evt);
            }
        });

        depth.setEditable(false);
        depth.setText("0");

        jLabel1.setText("%");

        jLabel2.setText("meters");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ppo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderOxygen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderDepth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Oxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sliderOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Oxygen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpleResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simpleResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cylinderPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Oxygen - Nitrogen Cylinder"));

        javax.swing.GroupLayout cylinderPanel1Layout = new javax.swing.GroupLayout(cylinderPanel1);
        cylinderPanel1.setLayout(cylinderPanel1Layout);
        cylinderPanel1Layout.setHorizontalGroup(
            cylinderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cylinderPanel1Layout.setVerticalGroup(
            cylinderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cylinderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cylinderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simple Calculations", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Complex Calculations"));

        jButton1.setText("Generate EAD Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate PPO2 Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        resultComplexCalculation.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        tableComplexCalculations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "D/O"
            }
        ));
        resultComplexCalculation.setViewportView(tableComplexCalculations);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Inputs"));

        inputsComplexCalculations.setBorder(javax.swing.BorderFactory.createTitledBorder("Oxigen"));

        label5.setText("Start:");

        sliderOxygenStart.setMajorTickSpacing(4);
        sliderOxygenStart.setMaximum(50);
        sliderOxygenStart.setMinimum(18);
        sliderOxygenStart.setMinorTickSpacing(1);
        sliderOxygenStart.setPaintLabels(true);
        sliderOxygenStart.setPaintTicks(true);
        sliderOxygenStart.setSnapToTicks(true);
        sliderOxygenStart.setToolTipText("");
        sliderOxygenStart.setValue(18);
        sliderOxygenStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderOxygenStartStateChanged(evt);
            }
        });

        OxygenStart.setEditable(false);
        OxygenStart.setText("18");

        jLabel3.setText("%");

        label9.setText("End:");

        sliderOxygenEnd.setMajorTickSpacing(4);
        sliderOxygenEnd.setMaximum(50);
        sliderOxygenEnd.setMinimum(18);
        sliderOxygenEnd.setMinorTickSpacing(1);
        sliderOxygenEnd.setPaintLabels(true);
        sliderOxygenEnd.setPaintTicks(true);
        sliderOxygenEnd.setSnapToTicks(true);
        sliderOxygenEnd.setToolTipText("");
        sliderOxygenEnd.setValue(18);
        sliderOxygenEnd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderOxygenEndStateChanged(evt);
            }
        });

        OxygenEnd.setEditable(false);
        OxygenEnd.setText("18");

        jLabel7.setText("%");

        javax.swing.GroupLayout inputsComplexCalculationsLayout = new javax.swing.GroupLayout(inputsComplexCalculations);
        inputsComplexCalculations.setLayout(inputsComplexCalculationsLayout);
        inputsComplexCalculationsLayout.setHorizontalGroup(
            inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsComplexCalculationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputsComplexCalculationsLayout.createSequentialGroup()
                        .addComponent(sliderOxygenStart, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OxygenStart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addGroup(inputsComplexCalculationsLayout.createSequentialGroup()
                        .addComponent(sliderOxygenEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OxygenEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputsComplexCalculationsLayout.setVerticalGroup(
            inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsComplexCalculationsLayout.createSequentialGroup()
                .addGroup(inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderOxygenStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputsComplexCalculationsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OxygenStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderOxygenEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputsComplexCalculationsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(inputsComplexCalculationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OxygenEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))))
        );

        inputsComplexCalculations1.setBorder(javax.swing.BorderFactory.createTitledBorder("Depth"));

        label8.setText("End:");

        sliderDepthEnd.setMajorTickSpacing(10);
        sliderDepthEnd.setMaximum(70);
        sliderDepthEnd.setMinimum(3);
        sliderDepthEnd.setMinorTickSpacing(1);
        sliderDepthEnd.setPaintLabels(true);
        sliderDepthEnd.setPaintTicks(true);
        sliderDepthEnd.setSnapToTicks(true);
        sliderDepthEnd.setToolTipText("");
        sliderDepthEnd.setValue(3);
        sliderDepthEnd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDepthEndStateChanged(evt);
            }
        });

        depthEnd.setEditable(false);
        depthEnd.setText("3");

        jLabel6.setText("meters");

        label10.setText("start:");

        sliderDepthStart.setMajorTickSpacing(10);
        sliderDepthStart.setMaximum(70);
        sliderDepthStart.setMinimum(3);
        sliderDepthStart.setMinorTickSpacing(1);
        sliderDepthStart.setPaintLabels(true);
        sliderDepthStart.setPaintTicks(true);
        sliderDepthStart.setSnapToTicks(true);
        sliderDepthStart.setToolTipText("");
        sliderDepthStart.setValue(3);
        sliderDepthStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDepthStartStateChanged(evt);
            }
        });

        depthStart.setEditable(false);
        depthStart.setText("3");

        jLabel8.setText("meters");

        javax.swing.GroupLayout inputsComplexCalculations1Layout = new javax.swing.GroupLayout(inputsComplexCalculations1);
        inputsComplexCalculations1.setLayout(inputsComplexCalculations1Layout);
        inputsComplexCalculations1Layout.setHorizontalGroup(
            inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                .addGroup(inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderDepthStart, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depthStart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8))
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderDepthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        inputsComplexCalculations1Layout.setVerticalGroup(
            inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                .addGroup(inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderDepthStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depthStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGroup(inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(inputsComplexCalculations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(inputsComplexCalculations1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderDepthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputsComplexCalculations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inputsComplexCalculations1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputsComplexCalculations1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputsComplexCalculations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultComplexCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultComplexCalculation, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Complex Calculations", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ppo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppo2ActionPerformed
        controller.setPPO2(Float.valueOf(ppo2.getSelectedItem().toString()));
    }//GEN-LAST:event_ppo2ActionPerformed

    private void sliderDepthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDepthStateChanged
        controller.setDepth(sliderDepth.getValue());
        depth.setText(String.valueOf(sliderDepth.getValue()));
    }//GEN-LAST:event_sliderDepthStateChanged

    private void sliderOxygenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderOxygenStateChanged
        controller.setOxygen(sliderOxygen.getValue());
        Oxygen.setText(String.valueOf(sliderOxygen.getValue()));
    }//GEN-LAST:event_sliderOxygenStateChanged

    private void eadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eadButtonActionPerformed
        simpleResult.setText(controller.eadCalculation());
    }//GEN-LAST:event_eadButtonActionPerformed

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        simpleResult.setText(controller.modCalculation());
    }//GEN-LAST:event_modButtonActionPerformed

    private void ppo2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppo2ButtonActionPerformed
        simpleResult.setText(controller.ppo2Calculation());
    }//GEN-LAST:event_ppo2ButtonActionPerformed

    private void bestMixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestMixButtonActionPerformed
        simpleResult.setText(controller.bestMixCalculation());
    }//GEN-LAST:event_bestMixButtonActionPerformed

    private void smodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smodButtonActionPerformed
        simpleResult.setText(controller.smodCalculation());
    }//GEN-LAST:event_smodButtonActionPerformed

    private void sliderOxygenStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderOxygenStartStateChanged
        controller.setOxygenStart(sliderOxygenStart.getValue());
        OxygenStart.setText(String.valueOf(sliderOxygenStart.getValue()));
        OxygenEnd.setText(String.valueOf(controller.getComplexCalculation().getOxygenEnd()));
        sliderOxygenEnd.setValue(controller.getComplexCalculation().getOxygenEnd());
    }//GEN-LAST:event_sliderOxygenStartStateChanged

    private void sliderDepthEndStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDepthEndStateChanged
        controller.setDepthEnd(sliderDepthEnd.getValue());
        depthEnd.setText(String.valueOf(sliderDepthEnd.getValue()));
        depthStart.setText(String.valueOf(controller.getComplexCalculation().getDepthStart()));
        sliderDepthStart.setValue(controller.getComplexCalculation().getDepthStart());
    }//GEN-LAST:event_sliderDepthEndStateChanged

    private void sliderOxygenEndStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderOxygenEndStateChanged
        controller.setOxygenEnd(sliderOxygenEnd.getValue());
        OxygenEnd.setText(String.valueOf(sliderOxygenEnd.getValue()));
        OxygenStart.setText(String.valueOf(controller.getComplexCalculation().getOxygenStart()));
        sliderOxygenStart.setValue(controller.getComplexCalculation().getOxygenStart());
    }//GEN-LAST:event_sliderOxygenEndStateChanged

    private void sliderDepthStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDepthStartStateChanged
        controller.setDepthStart(sliderDepthStart.getValue());
        depthStart.setText(String.valueOf(sliderDepthStart.getValue()));
        depthEnd.setText(String.valueOf(controller.getComplexCalculation().getDepthEnd()));
        sliderDepthEnd.setValue(controller.getComplexCalculation().getDepthEnd());
    }//GEN-LAST:event_sliderDepthStartStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.generateEADTable();
        // jScrollPane2.set
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.generatePPO2Table();
    }//GEN-LAST:event_jButton2ActionPerformed

    /*
     *Set values in view according to calculation     
     */
    public void setViewValues() {
        sliderDepth.setValue(Math.round(controller.getDepth()));
        sliderOxygen.setValue(controller.getOxygenInPercentage());
        ppo2.getModel().setSelectedItem(controller.getPPO2());
    }

    public JTable getTableComplexCalculations() {
        return tableComplexCalculations;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Oxygen;
    private java.awt.TextField OxygenEnd;
    private java.awt.TextField OxygenStart;
    private javax.swing.JButton bestMixButton;
    private view.CylinderPanel cylinderPanel1;
    private java.awt.TextField depth;
    private java.awt.TextField depthEnd;
    private java.awt.TextField depthStart;
    private javax.swing.JButton eadButton;
    private javax.swing.JPanel inputsComplexCalculations;
    private javax.swing.JPanel inputsComplexCalculations1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JButton modButton;
    private javax.swing.JComboBox ppo2;
    private javax.swing.JButton ppo2Button;
    private javax.swing.JScrollPane resultComplexCalculation;
    private javax.swing.JLabel simpleResult;
    private javax.swing.JSlider sliderDepth;
    private javax.swing.JSlider sliderDepthEnd;
    private javax.swing.JSlider sliderDepthStart;
    private javax.swing.JSlider sliderOxygen;
    private javax.swing.JSlider sliderOxygenEnd;
    private javax.swing.JSlider sliderOxygenStart;
    private javax.swing.JButton smodButton;
    private javax.swing.JTable tableComplexCalculations;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getResultComplexCalculation() {
        return resultComplexCalculation;
    }

}
